import Container from '@/components/container';
import Footer from '@/components/footer';
import Header from '@/components/header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// metadatayı burada tanımlarsak bütün proje için çalışır
// her sayfa için ayrı tanım da yapılabilir
// tek bir sayfa için ayrı tanım da yapılabilir
export const metadata: Metadata = {
  title: 'NextJS Full Stack Project',
  description: 'Generated by create next app',
};

// layout sayfası projenin root alanıdır
// children ise route sayfalarıdır, bu sayfalar folder şeklinde tanımlanmalıdır, sayfa tanımı page.tsx şeklinde olmalıdır
// Header , Footer her sayfada çalışacak yerleri direkt burada tanımlayabiliriz children altında veya üstünde
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-zinc-100 text-zinc-900 min-h-screen`}
      >
        {/* Sayfa belirli standartalrda gözüksün diye kendi container yarattım */}
        <Container>
          <Header />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
